export default 

	[{
		"currentPage": 1,
		"total": 80,
		"pageSize": 10,
		"totalPage": 8,
		"rows": [{
            "sys_name":"BA",
            "brand":"江森",
            "supplier":"上海庄生机电工程设备有限公司",
            "link_man":"周娇",
            "phone":"周：15655194420",
            "payment_type":"预付30%，余70%货到6个月支付",
            "is_use":"有效"
            },
            {
            "sys_name":"BA",
            "brand":"霍尼",
            "supplier":"合肥宇聪电子科技有限公司",
            "link_man":"吴小胜",
            "phone":"吴：15850558314",
            "payment_type":"预付30%，余70%货到6个月支付",
            "is_use":"有效"
            },
            {
            "sys_name":"ICU",
            "brand":"来邦",
            "supplier":"来邦科技股份公司",
            "link_man":"叶丹",
            "phone":"叶丹：13632591193",
            "payment_type":"现款现货",
            "is_use":"有效"
            },
            {
            "sys_name":"ICU",
            "brand":"美一",
            "supplier":"福建环宇通信息科技股份公司",
            "link_man":"骆经理",
            "phone":"骆：18050800655",
            "payment_type":"现款现货",
            "is_use":"有效"
            },
            {
            "sys_name":"UPS",
            "brand":"易事特",
            "supplier":"易事特集团股份有限公司",
            "link_man":"石经理",
            "phone":"石：18297972985",
            "payment_type":"预付30%，余70%货到6个月支付6个月承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"UPS",
            "brand":"英威腾",
            "supplier":"深圳市英威腾电源有限公司",
            "link_man":"史鑫",
            "phone":"史：18715071357",
            "payment_type":"预付30%，余70%货到6个月支付6个月承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"报警",
            "brand":"博世",
            "supplier":"合肥福克斯安防智能科技有限公司",
            "link_man":"杨辉",
            "phone":"杨：13739280671",
            "payment_type":"货到3个月",
            "is_use":"有效"
            },
            {
            "sys_name":"报警",
            "brand":"霍尼",
            "supplier":"合肥福克斯安防智能科技有限公司",
            "link_man":"杨辉",
            "phone":"杨：13739280671",
            "payment_type":"货到3个月",
            "is_use":"有效"
            },
            {
            "sys_name":"报警",
            "brand":"福克斯",
            "supplier":"合肥福克斯安防智能科技有限公司",
            "link_man":"陈家龙",
            "phone":"陈：18755175938",
            "payment_type":"货到3个月",
            "is_use":"有效"
            },
            {
            "sys_name":"病房呼叫",
            "brand":"南格",
            "supplier":"北京鑫丰南格科技有限责任公司",
            "link_man":"王经理",
            "phone":"王：18672294286",
            "payment_type":"现款现货",
            "is_use":"有效"
            }
		],
		"start": 0
	},

	{
		"currentPage": 2,
		"total": 80,
		"pageSize": 10,
		"totalPage": 8,
		"rows": [ {
            "sys_name":"病房呼叫",
            "brand":"德亮",
            "supplier":"深圳鑫德亮电子有限公司",
            "link_man":"尹经理",
            "phone":"尹：13682319357",
            "payment_type":"现款现货",
            "is_use":"有效"
            },
            {
            "sys_name":"场地扩声",
            "brand":"科大乾延",
            "supplier":"安徽天迈宝智能科技有限公司",
            "link_man":"冯经理",
            "phone":"冯：18019924050",
            "payment_type":"预付30%，货到且安装调试完成验收合格后，30天内支付12个月银行承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"场馆照明",
            "brand":"海洋王",
            "supplier":"海洋王照明科技股份有限公司",
            "link_man":"潘经理",
            "phone":"潘：18105710007",
            "payment_type":"验收合格后支付",
            "is_use":"有效"
            },
            {
            "sys_name":"场馆照明",
            "brand":"飞利浦",
            "supplier":"南京思达威建筑装饰工程有限公司",
            "link_man":"卢经理",
            "phone":"卢：13851495008",
            "payment_type":"预付15%，安装通电72小时后经甲方验收合格付45%（35%转账，10%为6各月份银行承兑），全部验收合格后付35%（6个月银行承兑）。5%质保一年支付",
            "is_use":"有效"
            },
            {
            "sys_name":"窗口对讲",
            "brand":"美一",
            "supplier":"福建环宇通信息科技股份公司",
            "link_man":"骆经理",
            "phone":"骆：18050800655",
            "payment_type":"现款现货",
            "is_use":"有效"
            },
            {
            "sys_name":"大屏",
            "brand":"极光",
            "supplier":"深圳极光王科技股份有限公司",
            "link_man":"王经理",
            "phone":"王：18026908268",
            "payment_type":"预付40%，亮屏六个月支付55%（承兑或转账），余5%质保2年（自亮屏起）亮屏你们出示盖章的亮屏验收凭证文件。",
            "is_use":"有效"
            },
            {
            "sys_name":"大屏",
            "brand":"蓝普",
            "supplier":"安徽光巽智能科技股份有限公司",
            "link_man":"许经理",
            "phone":"许：13395518363",
            "payment_type":"?预付30%，亮屏，调试完成后6个月支付65%，留5%，项目验收合格后一年支付",
            "is_use":"有效"
            },
            {
            "sys_name":"电视转播",
            "brand":"弘元鑫",
            "supplier":"深圳市弘元鑫光电科技有限公司",
            "link_man":"邓荷萍",
            "phone":"邓荷萍：15818752823",
            "payment_type":"预付50%，验收合格后4个月支付50%，6个月银行承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"电子班牌",
            "brand":"科讯",
            "supplier":"安徽省科迅教育装备有限公司",
            "link_man":"吴海燕",
            "phone":"吴海燕：15375057262",
            "payment_type":"现款现货",
            "is_use":"有效"
            },
            {
            "sys_name":"电子班牌",
            "brand":"林乔",
            "supplier":"安徽恩凡智能科技工程有限公司",
            "link_man":"陈总",
            "phone":"陈总：15855105287",
            "payment_type":"预付30%，余下70%货到3个月付清货款",
            "is_use":"有效"
            }
		],
		"start": 0
	},{
		"currentPage": 3,
		"total": 80,
		"pageSize": 10,
		"totalPage": 8,
		"rows": [{
            "sys_name":"动环",
            "brand":"英维克",
            "supplier":"深圳市英维克科技股份有限公司",
            "link_man":"孙本云",
            "phone":"孙：15056004400",
            "payment_type":"预付20%，货到6个月80%支付6-12个月承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"多媒体教学",
            "brand":"盈可视",
            "supplier":"广州盈可视电子科技有限公司",
            "link_man":"严璐",
            "phone":"严璐 ：18949808018",
            "payment_type":"预付30%  余下70%货到1个月付清货款",
            "is_use":"有效"
            },
            {
            "sys_name":"多媒体教学",
            "brand":"海信",
            "supplier":"安徽恩凡智能科技工程有限公司",
            "link_man":"陈总",
            "phone":"陈总：15855105287",
            "payment_type":"预付30%，余下70%货到3个月付清货款",
            "is_use":"有效"
            },
            {
            "sys_name":"服务器",
            "brand":"浪潮",
            "supplier":"安徽中康普智信息技术有限责任公司",
            "link_man":"宁本余",
            "phone":"宁本余：13965147275",
            "payment_type":"货到后3个月",
            "is_use":"有效"
            },
            {
            "sys_name":"公共广播",
            "brand":"升谱达",
            "supplier":"合肥音视特信息科技有限公司",
            "link_man":"汪经理",
            "phone":"汪：18019984559",
            "payment_type":"货到6个月支付6个月银行承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"公共广播",
            "brand":"BGM",
            "supplier":"南京艾利丰信息科技有限公司",
            "link_man":"赵经理",
            "phone":"赵：13865801099",
            "payment_type":"预付30%，余70%货到4个月支付",
            "is_use":"有效"
            },
            {
            "sys_name":"管",
            "brand":"国产",
            "supplier":"马鞍山市大向贸易有限公司",
            "link_man":"周明",
            "phone":"周明：13013116358",
            "payment_type":"预付20%，余80%货到3个月支付",
            "is_use":"有效"
            },
            {
            "sys_name":"管",
            "brand":"国产",
            "supplier":"芜湖天一桥架制造有限公司",
            "link_man":"历总",
            "phone":"历：13721217373",
            "payment_type":"预付20%，余80%货到3个月支付",
            "is_use":"有效"
            },
            {
            "sys_name":"会议",
            "brand":"科大乾延",
            "supplier":"安徽天迈宝智能科技有限公司",
            "link_man":"冯经理",
            "phone":"冯：18019924050",
            "payment_type":"预付30%，货到且安装调试完成验收合格后，30天内支付12个月银行承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"机房装饰装修",
            "brand":"勤诚",
            "supplier":"合肥勤诚电子科技有限公司",
            "link_man":"王松",
            "phone":"王松： 18055169626",
            "payment_type":"合同签订后立即进场施工，完成清单内所有墙面和顶面后支付30%，完成所有地面设备材料安装施工后再付40%，剩余25%经三方验收后支付，最后5%6个月账期",
            "is_use":"有效"
            }
		],
		"start": 0
	},{
		"currentPage": 4,
		"total": 80,
		"pageSize": 10,
		"totalPage": 8,
		"rows": [{
            "sys_name":"机房装饰装修",
            "brand":"朗瑞",
            "supplier":"合肥朗瑞电源科技有限公司",
            "link_man":"方总",
            "phone":"方：18095652119",
            "payment_type":"合同签订后立即进场施工，完成清单内所有墙面和顶面后支付30%，完成所有地面设备材料安装施工后再付40%，剩余25%经三方验收后支付，最后5%6个月账期",
            "is_use":"有效"
            },
            {
            "sys_name":"机房装饰装修",
            "brand":"鸿联",
            "supplier":"合肥鸿联机房设备工程有限公司",
            "link_man":"孟总",
            "phone":"孟：13905603016",
            "payment_type":"合同签订后立即进场施工，完成清单内所有墙面和顶面后支付30%，完成所有地面设备材料安装施工后再付40%，剩余25%经三方验收后支付，最后5%6个月账期",
            "is_use":"有效"
            },
            {
            "sys_name":"计时计分",
            "brand":"易彩通",
            "supplier":"北京易彩通科技有限责任公司",
            "link_man":"张琪",
            "phone":"张琪：13466702411",
            "payment_type":"预付30%，货到20%，验收合格后3个月支付50%",
            "is_use":"有效"
            },
            {
            "sys_name":"监控",
            "brand":"宇视",
            "supplier":"广州新科佳都科技有限公司",
            "link_man":"孔新义",
            "phone":"孔：15209822221",
            "payment_type":"货到6个月",
            "is_use":"有效"
            },
            {
            "sys_name":"监控",
            "brand":"大华",
            "supplier":"浙江大华科技有限公司",
            "link_man":"袁瑞",
            "phone":"袁瑞：18969076315",
            "payment_type":"货到6个月支付6个月银行承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"精密空调",
            "brand":"英维克",
            "supplier":"深圳市英维克科技股份有限公司",
            "link_man":"孙本云",
            "phone":"孙：15056004400",
            "payment_type":"预付20%，货到6个月80%支付6-12个月承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"考务广播",
            "brand":"升谱达",
            "supplier":"合肥音视特信息科技有限公司",
            "link_man":"汪经理",
            "phone":"汪：18019984559",
            "payment_type":"货到6个月支付6个月银行承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"考务监控",
            "brand":"竞业达",
            "supplier":"北京竞业达数字系统科技有限公司",
            "link_man":"武经理",
            "phone":"武经理：13965116350",
            "payment_type":"合同签订之后 7 个工作日内收到乙方开具的等额发票后支付80%的合同货款至乙方，剩余的20%货款在货到票齐且甲方验收货物无误之后10个工作日内支付",
            "is_use":"有效"
            },
            {
            "sys_name":"可视对讲",
            "brand":"大华",
            "supplier":"浙江大华科技有限公司",
            "link_man":"袁瑞",
            "phone":"袁瑞：18969076315",
            "payment_type":"货到6个月支付6个月银行承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"冷通道",
            "brand":"英维克",
            "supplier":"深圳市英维克科技股份有限公司",
            "link_man":"孙本云",
            "phone":"孙：15056004400",
            "payment_type":"预付20%，货到6个月80%支付6-12个月承兑",
            "is_use":"有效"
            }
		],
		"start": 0
	},{
		"currentPage": 5,
		"total": 80,
		"pageSize": 10,
		"totalPage": 8,
		"rows": [{
            "sys_name":"录播",
            "brand":"盈可视",
            "supplier":"广州盈可视电子科技有限公司",
            "link_man":"严璐",
            "phone":"严璐 ：18949808018",
            "payment_type":"预付30%  余下70%货到1个月付清货款",
            "is_use":"有效"
            },
            {
            "sys_name":"录播",
            "brand":"快鱼",
            "supplier":"北京快鱼电子股份有限公司",
            "link_man":"刘伟",
            "phone":"刘伟：15856908286",
            "payment_type":"预付30%，余下70%货到6个月付清货款",
            "is_use":"有效"
            },
            {
            "sys_name":"录播",
            "brand":"大华",
            "supplier":"浙江大华科技有限公司",
            "link_man":"袁瑞",
            "phone":"袁瑞：18969076315",
            "payment_type":"货到6个月支付6个月银行承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"门禁",
            "brand":"达实",
            "supplier":"深圳达实信息技术有限公司",
            "link_man":"卢兆凯",
            "phone":"卢兆凯：13866141931",
            "payment_type":"货到6个月账期支付6个月承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"门禁",
            "brand":"立方",
            "supplier":"合肥立脉电子技术有限公司",
            "link_man":"汤江龙",
            "phone":"汤江龙：15955120114",
            "payment_type":"预付30%，余70%货到6个月支付",
            "is_use":"有效"
            },
            {
            "sys_name":"能耗",
            "brand":"瑞信",
            "supplier":"常州瑞信电子科技有限公司",
            "link_man":"周业勇",
            "phone":"周：18018262988",
            "payment_type":"预付30%，余70%货到6个月支付",
            "is_use":"有效"
            },
            {
            "sys_name":"排队叫号",
            "brand":"星际互动",
            "supplier":"武汉星际互动智能技术有限公司",
            "link_man":"杨经理",
            "phone":"杨：15972967910",
            "payment_type":"预付30%，余下70%货到6个月付清货款",
            "is_use":"有效"
            },
            {
            "sys_name":"配电柜",
            "brand":"施耐德",
            "supplier":"合肥鸿联机房设备工程有限公司",
            "link_man":"孟总",
            "phone":"孟：13905603016",
            "payment_type":"合同签订后立即进场施工，完成清单内所有墙面和顶面后支付30%，完成所有地面设备材料安装施工后再付40%，剩余25%经三方验收后支付，最后5%6个月账期",
            "is_use":"有效"
            },
            {
            "sys_name":"配电柜",
            "brand":"施耐德",
            "supplier":"马鞍山市锦宇机械电器有限公司",
            "link_man":"黄总",
            "phone":"黄总18055508222",
            "payment_type":"预付30%，余下70%货到3个月付清货款",
            "is_use":"有效"
            },
            {
            "sys_name":"桥架",
            "brand":"国产",
            "supplier":"马鞍山市大向贸易有限公司",
            "link_man":"周明",
            "phone":"周明：13013116358",
            "payment_type":"预付20%，余80%货到3个月支付",
            "is_use":"有效"
            }
		],
		"start": 0
	},{
		"currentPage": 6,
		"total": 80,
		"pageSize": 10,
		"totalPage": 8,
		"rows": [{
            "sys_name":"桥架",
            "brand":"国产",
            "supplier":"芜湖天一桥架制造有限公司",
            "link_man":"历总",
            "phone":"历：13721217373",
            "payment_type":"预付20%，余80%货到6个月支付",
            "is_use":"有效"
            },
            {
            "sys_name":"弱电线缆",
            "brand":"天诚",
            "supplier":"南京天诚智汇电子科技有限公司",
            "link_man":"刘瑜",
            "phone":"刘：13218021233",
            "payment_type":"预付20%，余80%货到6个月，支付6个月银行承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"弱电线缆",
            "brand":"友创",
            "supplier":"江苏友创光电科技有限公司",
            "link_man":"朱经理",
            "phone":"朱：18956220228",
            "payment_type":"货到后6个月账期，支付方式6个月银行承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"弱电线缆",
            "brand":"天帝",
            "supplier":"扬州驰天电子有限公司",
            "link_man":"姜友春",
            "phone":"姜友春：15950589587",
            "payment_type":"货到后9个月账期，支付方式6个月银行承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"升旗",
            "brand":"易彩通",
            "supplier":"北京易彩通科技有限责任公司",
            "link_man":"张琪",
            "phone":"张琪：13466702411",
            "payment_type":"预付30%，货到20%，验收合格后3个月支付50%",
            "is_use":"有效"
            },
            {
            "sys_name":"升旗",
            "brand":"奥天",
            "supplier":"广州市奥天旗杆有限公司",
            "link_man":"卓四英",
            "phone":"卓四英：13826484918",
            "payment_type":"预付30%，货到50%，调试验收合格后3个月支付20%",
            "is_use":"有效"
            },
            {
            "sys_name":"手术示教",
            "brand":"盈可视",
            "supplier":"广州盈可视电子科技有限公司",
            "link_man":"严璐",
            "phone":"严璐 ：18949808018",
            "payment_type":"预付30%  余下70%货到1个月付清货款",
            "is_use":"有效"
            },
            {
            "sys_name":"停车场",
            "brand":"科拓",
            "supplier":"合肥舒泊智能科技有限公司",
            "link_man":"盛经理",
            "phone":"盛：18156538152",
            "payment_type":"预付30%，货到20%，剩余2个月内支付70%",
            "is_use":"有效"
            },
            {
            "sys_name":"停车场",
            "brand":"立方",
            "supplier":"合肥立脉电子技术有限公司",
            "link_man":"汤江龙",
            "phone":"汤江龙：15955120114",
            "payment_type":"预付30%，余70%货到6个月支付",
            "is_use":"有效"
            },
            {
            "sys_name":"网络",
            "brand":"锐捷",
            "supplier":"合肥正达智控信息工程有限公司",
            "link_man":"孙敬恭",
            "phone":"孙敬恭：13451828168",
            "payment_type":"预付30%，余70%货到6个月支付",
            "is_use":"有效"
            }
		],
		"start": 0
	},{
		"currentPage": 7,
		"total": 80,
		"pageSize": 10,
		"totalPage": 8,
		"rows": [{
            "sys_name":"无线对讲",
            "brand":"摩托罗拉",
            "supplier":"上海申奇通信设备有限公司",
            "link_man":"徐世杰",
            "phone":"徐：18939822145",
            "payment_type":"预付30%，货到6个月70%支付6个月承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"无线对讲",
            "brand":"海能达",
            "supplier":"上海申奇通信设备有限公司",
            "link_man":"徐世杰",
            "phone":"徐：18939822145",
            "payment_type":"预付30%，货到6个月70%支付6个月承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"无线对讲",
            "brand":"科立讯",
            "supplier":"上海申奇通信设备有限公司",
            "link_man":"徐世杰",
            "phone":"徐：18939822145",
            "payment_type":"预付30%，货到6个月70%支付6个月承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"系统集成",
            "brand":"五岳",
            "supplier":"西安五岳软件科技有限公司",
            "link_man":"邱鹏",
            "phone":"邱鹏：13524639045",
            "payment_type":"预付30%，余下70%安装调试完毕6个月支付",
            "is_use":"有效"
            },
            {
            "sys_name":"校园电台",
            "brand":"迪乐普",
            "supplier":"深圳迪乐普数码科技有限公司",
            "link_man":"刘经理",
            "phone":"刘：13622239770",
            "payment_type":"现款现货",
            "is_use":"有效"
            },
            {
            "sys_name":"校园管理平台",
            "brand":"科讯",
            "supplier":"安徽省科迅教育装备有限公司",
            "link_man":"吴海燕",
            "phone":"吴海燕：15375057262",
            "payment_type":"现款现货",
            "is_use":"有效"
            },
            {
            "sys_name":"信息发布",
            "brand":"星际互动",
            "supplier":"武汉星际互动智能技术有限公司",
            "link_man":"杨经理",
            "phone":"杨：15972967910",
            "payment_type":"预付30%，余下70%货到6个月付清货款",
            "is_use":"有效"
            },
            {
            "sys_name":"巡更",
            "brand":"慧友安",
            "supplier":"深圳市惠友安电子技术有限公司",
            "link_man":"刘经理",
            "phone":"刘：15920097136",
            "payment_type":"现款现货",
            "is_use":"有效"
            },
            {
            "sys_name":"巡更",
            "brand":"兰德华",
            "supplier":"上海际卡电子有限公司",
            "link_man":"马新瑞",
            "phone":"马经理:13916808585,18917989947",
            "payment_type":"现款现货",
            "is_use":"有效"
            },
            {
            "sys_name":"一氧化碳二氧化碳监测",
            "brand":"图久",
            "supplier":"合肥图久智能科技有限公司",
            "link_man":"张燕舞",
            "phone":"张燕舞：15077906693",
            "payment_type":"合同签订预付30% 货到现场后一周内支付20%到货款，余款40%货到现场之日起4个月账期，余下10%质保一年",
            "is_use":"有效"
            }
		],
		"start": 0
	},{
		"currentPage": 8,
		"total": 80,
		"pageSize": 10,
		"totalPage": 8,
		"rows": [{
            "sys_name":"一氧化碳二氧化碳监测",
            "brand":"源控",
            "supplier":"上海源控自动化技术有限公司",
            "link_man":"万实现",
            "phone":"万实现：15856948512",
            "payment_type":"预付30%，余下70%货到6个月付清货款",
            "is_use":"有效"
            },
            {
            "sys_name":"婴儿防盗",
            "brand":"Rexense",
            "supplier":"浙江瑞瀛物联科技有限公司，",
            "link_man":"沈经理",
            "phone":"沈：18957168068",
            "payment_type":"现款现货",
            "is_use":"有效"
            },
            {
            "sys_name":"影像回放",
            "brand":"天影视通",
            "supplier":"北京天影视通科技有限公司",
            "link_man":"段经理",
            "phone":"段：18618410741",
            "payment_type":"现款现货",
            "is_use":"有效"
            },
            {
            "sys_name":"智能照明",
            "brand":"毅德",
            "supplier":"合肥福克斯安防智能科技有限公司",
            "link_man":"杨总",
            "phone":"杨总：13739280671",
            "payment_type":"货到后6个月内付清货款",
            "is_use":"有效"
            },
            {
            "sys_name":"智能照明",
            "brand":"纳宇",
            "supplier":"上海纳宇电气有限公司",
            "link_man":"李龙龙",
            "phone":"李龙龙：13965090466",
            "payment_type":"6个月账期，到期支付6个月银行承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"周界防范（电子围栏）",
            "brand":"ANENC",
            "supplier":"合肥福克斯安防智能科技有限公司",
            "link_man":"陈家龙",
            "phone":"陈家龙：15055118081",
            "payment_type":"货到后6个月内付清货款",
            "is_use":"有效"
            },
            {
            "sys_name":"子母钟",
            "brand":"岭通",
            "supplier":"上海岭通电子科技有限公司",
            "link_man":"施总",
            "phone":"施总：13371806433",
            "payment_type":"预付30%，余下70%货到3个月付清货款  支付方式为6个月银行承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"子母钟",
            "brand":"北极星",
            "supplier":"南京玛卡鲁智能科技有限公司",
            "link_man":"隋永见",
            "phone":"隋永见：18561005859",
            "payment_type":"预付30%，货到后6个月支付65%，5%调试合格后一年内支付",
            "is_use":"有效"
            },
            {
            "sys_name":"综合布线",
            "brand":"天诚",
            "supplier":"南京天诚智汇电子科技有限公司",
            "link_man":"刘瑜",
            "phone":"刘：13218021233",
            "payment_type":"预付20%，余80%货到6个月，支付6个月银行承兑",
            "is_use":"有效"
            },
            {
            "sys_name":"综合布线",
            "brand":"派斯莱克",
            "supplier":"犹厮奈驰（上海）网络科技有限公司",
            "link_man":"徐总",
            "phone":"徐总：13801992322",
            "payment_type":"货到12个月支付6个月银行承兑",
            "is_use":"有效"
            }
		],
		"start": 0
	}]
